In [1]:
!pip install nltk

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter #Counts frequency of elements in a list or text.
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize  #Splits text into individual words/tokens.
import nltk # Used for NLP tasks like tokenization, stemming, stopword removal, etc

In [3]:
document = """The Last Train Journey

On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.
The station was nearly empty except for a few passengers waiting quietly on wooden benches.
A loud whistle echoed through the air as the final train of the night slowly entered the platform.

Daniel checked the ticket in his pocket and walked toward the train.
The metal doors opened with a creaking sound and warm air rushed outside.
Inside the train, yellow lights flickered softly above rows of empty seats.

He chose a seat beside the window and placed his bag carefully near his feet.
As the train began to move, the city lights slowly disappeared behind thick clouds of fog.
Snow started falling gently outside while distant mountains appeared under the moonlight.

Across the aisle sat an elderly woman reading an old book with a blue cover.
Every few minutes she looked outside the window as if searching for something familiar.
Daniel noticed a silver necklace around her neck shaped like a small compass.

After several hours, the train stopped at a remote station surrounded by tall pine trees.
Very few people entered or left the train at that place.
A strange silence covered the station as the doors closed once again.

Curious about the woman, Daniel finally started a conversation.
The woman introduced herself as Eleanor and explained that she was returning to her hometown after many years.
She said the town was hidden deep within the northern mountains and was known for its beautiful frozen lake.

As the journey continued, Eleanor shared stories from her childhood.
She described colorful festivals, music performances, and lanterns floating across the lake during winter nights.
Daniel listened carefully while the train moved through snowy valleys and dark forests.

Near midnight, the train suddenly slowed down because heavy snow had covered the tracks ahead.
Passengers became nervous and began discussing possible delays.
Conductors moved through the cabins trying to calm everyone.

Daniel looked outside and saw workers removing snow under bright floodlights.
The freezing wind shook the train slightly while snow continued falling from the dark sky.
Despite the delay, Eleanor remained calm and continued telling her stories.

Several hours later, the tracks were finally cleared and the train resumed its journey.
The passengers sighed with relief as warm coffee was served throughout the cabins.
Daniel and Eleanor continued talking about travel, history, and forgotten places around the world.

Just before sunrise, the train reached the mountain town.
The station was small but beautifully decorated with glowing lamps and snow-covered rooftops.
People wearing thick winter coats walked slowly across the icy streets.

Before leaving, Eleanor handed Daniel a folded piece of paper.
Inside it was a drawing of the frozen lake along with a short message thanking him for the conversation.
Daniel smiled and carefully placed the paper inside his notebook.

As the train departed once again, Daniel stood on the platform watching the sunrise over the mountains.
The cold air, quiet streets, and distant church bells created a peaceful atmosphere he would never forget.
Years later, Daniel would still remember that mysterious winter journey and the stories shared by Eleanor on the last train of the night.
"""

In [4]:
# NLTK does NOT come with pretrained tokenizers by default.

# Tokenization
nltk.download('punkt')

# Some newer NLTK versions require additional tokenizer tables.
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

# Tokenizer

In [5]:
tokens = word_tokenize(document.lower())
tokens

['the',
 'last',
 'train',
 'journey',
 'on',
 'a',
 'cold',
 'winter',
 'evening',
 ',',
 'daniel',
 'arrived',
 'at',
 'the',
 'old',
 'railway',
 'station',
 'carrying',
 'a',
 'small',
 'leather',
 'bag',
 '.',
 'the',
 'station',
 'was',
 'nearly',
 'empty',
 'except',
 'for',
 'a',
 'few',
 'passengers',
 'waiting',
 'quietly',
 'on',
 'wooden',
 'benches',
 '.',
 'a',
 'loud',
 'whistle',
 'echoed',
 'through',
 'the',
 'air',
 'as',
 'the',
 'final',
 'train',
 'of',
 'the',
 'night',
 'slowly',
 'entered',
 'the',
 'platform',
 '.',
 'daniel',
 'checked',
 'the',
 'ticket',
 'in',
 'his',
 'pocket',
 'and',
 'walked',
 'toward',
 'the',
 'train',
 '.',
 'the',
 'metal',
 'doors',
 'opened',
 'with',
 'a',
 'creaking',
 'sound',
 'and',
 'warm',
 'air',
 'rushed',
 'outside',
 '.',
 'inside',
 'the',
 'train',
 ',',
 'yellow',
 'lights',
 'flickered',
 'softly',
 'above',
 'rows',
 'of',
 'empty',
 'seats',
 '.',
 'he',
 'chose',
 'a',
 'seat',
 'beside',
 'the',
 'window',
 'a

# Build Vocabs

In [6]:
vocab = {'<unk>' : 0}

In [7]:
for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token] = len(vocab)

vocab

{'<unk>': 0,
 'the': 1,
 'last': 2,
 'train': 3,
 'journey': 4,
 'on': 5,
 'a': 6,
 'cold': 7,
 'winter': 8,
 'evening': 9,
 ',': 10,
 'daniel': 11,
 'arrived': 12,
 'at': 13,
 'old': 14,
 'railway': 15,
 'station': 16,
 'carrying': 17,
 'small': 18,
 'leather': 19,
 'bag': 20,
 '.': 21,
 'was': 22,
 'nearly': 23,
 'empty': 24,
 'except': 25,
 'for': 26,
 'few': 27,
 'passengers': 28,
 'waiting': 29,
 'quietly': 30,
 'wooden': 31,
 'benches': 32,
 'loud': 33,
 'whistle': 34,
 'echoed': 35,
 'through': 36,
 'air': 37,
 'as': 38,
 'final': 39,
 'of': 40,
 'night': 41,
 'slowly': 42,
 'entered': 43,
 'platform': 44,
 'checked': 45,
 'ticket': 46,
 'in': 47,
 'his': 48,
 'pocket': 49,
 'and': 50,
 'walked': 51,
 'toward': 52,
 'metal': 53,
 'doors': 54,
 'opened': 55,
 'with': 56,
 'creaking': 57,
 'sound': 58,
 'warm': 59,
 'rushed': 60,
 'outside': 61,
 'inside': 62,
 'yellow': 63,
 'lights': 64,
 'flickered': 65,
 'softly': 66,
 'above': 67,
 'rows': 68,
 'seats': 69,
 'he': 70,
 'chose

In [8]:
len(vocab)

284

# Extract sentence from data

In [9]:
input_sentences = document.split('\n')

In [10]:
input_sentences

['The Last Train Journey',
 '',
 'On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.',
 'The station was nearly empty except for a few passengers waiting quietly on wooden benches.',
 'A loud whistle echoed through the air as the final train of the night slowly entered the platform.',
 '',
 'Daniel checked the ticket in his pocket and walked toward the train.',
 'The metal doors opened with a creaking sound and warm air rushed outside.',
 'Inside the train, yellow lights flickered softly above rows of empty seats.',
 '',
 'He chose a seat beside the window and placed his bag carefully near his feet.',
 'As the train began to move, the city lights slowly disappeared behind thick clouds of fog.',
 'Snow started falling gently outside while distant mountains appeared under the moonlight.',
 '',
 'Across the aisle sat an elderly woman reading an old book with a blue cover.',
 'Every few minutes she looked outside the window as if searching for

In [11]:
input_sentences[2]

'On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.'

In [12]:
def text_to_indices(sentence, vocab):
  numerical_sentence = []
  for token in sentence:
    if token in vocab:
      numerical_sentence.append(vocab[token])
    else:
      numerical_sentence.append(vocab['<unk>'])

  return numerical_sentence

In [13]:
input_numerical_sentence= []
for sentence in input_sentences:
  input_numerical_sentence.append(text_to_indices(word_tokenize(sentence.lower()), vocab))

In [14]:
input_numerical_sentence

[[1, 2, 3, 4],
 [],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20, 21],
 [1, 16, 22, 23, 24, 25, 26, 6, 27, 28, 29, 30, 5, 31, 32, 21],
 [6, 33, 34, 35, 36, 1, 37, 38, 1, 39, 3, 40, 1, 41, 42, 43, 1, 44, 21],
 [],
 [11, 45, 1, 46, 47, 48, 49, 50, 51, 52, 1, 3, 21],
 [1, 53, 54, 55, 56, 6, 57, 58, 50, 59, 37, 60, 61, 21],
 [62, 1, 3, 10, 63, 64, 65, 66, 67, 68, 40, 24, 69, 21],
 [],
 [70, 71, 6, 72, 73, 1, 74, 50, 75, 48, 20, 76, 77, 48, 78, 21],
 [38, 1, 3, 79, 80, 81, 10, 1, 82, 64, 42, 83, 84, 85, 86, 40, 87, 21],
 [88, 89, 90, 91, 61, 92, 93, 94, 95, 96, 1, 97, 21],
 [],
 [98, 1, 99, 100, 101, 102, 103, 104, 101, 14, 105, 56, 6, 106, 107, 21],
 [108, 27, 109, 110, 111, 61, 1, 74, 38, 112, 113, 26, 114, 115, 21],
 [11, 116, 6, 117, 118, 119, 120, 121, 122, 123, 6, 18, 124, 21],
 [],
 [125, 126, 127, 10, 1, 3, 128, 13, 6, 129, 16, 130, 131, 132, 133, 134, 21],
 [135, 27, 136, 43, 137, 138, 1, 3, 13, 139, 140, 21],
 [6, 141, 142, 143, 1, 16, 38, 1, 54, 144, 145, 146

# Training Sequence Form

In [15]:
training_sequence = []
for sentence in input_numerical_sentence:
  for i in range(1, len(sentence)):
    training_sequence.append(sentence[:i+1])

In [16]:
training_sequence

[[1, 2],
 [1, 2, 3],
 [1, 2, 3, 4],
 [5, 6],
 [5, 6, 7],
 [5, 6, 7, 8],
 [5, 6, 7, 8, 9],
 [5, 6, 7, 8, 9, 10],
 [5, 6, 7, 8, 9, 10, 11],
 [5, 6, 7, 8, 9, 10, 11, 12],
 [5, 6, 7, 8, 9, 10, 11, 12, 13],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20, 21],
 [1, 16],
 [1, 16, 22],
 [1, 16, 22, 23],
 [1, 16, 22, 23, 24],
 [1, 16, 22, 23, 24, 25],
 [1, 16, 22, 23, 24, 25, 26],
 [1, 16, 22, 23, 24, 25, 26, 6],
 [1, 16, 22, 23, 24, 25, 26, 6, 27],
 [1, 16, 22, 23, 24, 25, 26, 6, 27, 28],
 [1, 16, 22, 23, 24, 2

In [17]:
len(training_sequence)

555

In [18]:
training_sequence[:5]

[[1, 2], [1, 2, 3], [1, 2, 3, 4], [5, 6], [5, 6, 7]]

In [19]:
len_list = []
for sequence in training_sequence:
  len_list.append(len(sequence))

In [20]:
max(len_list)

25

In [21]:
training_sequence[0]

[1, 2]

In [22]:
padded_training_sequence = []
for sequence in training_sequence:
  padded_training_sequence.append( [0]* (max(len_list)-len(sequence)) + sequence  )

In [23]:
len(padded_training_sequence[0])

25

In [24]:
padded_training_sequence[0]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]

In [25]:
padded_training_sequence[6]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 8, 9]

# Tensor Convert

In [26]:
padded_training_sequence = torch.tensor(padded_training_sequence, dtype= torch.long)

In [27]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   2,   3,   4],
        ...,
        [  0,   0, 158,  ...,   3,  40,   1],
        [  0, 158, 223,  ...,  40,   1,  41],
        [158, 223,  10,  ...,   1,  41,  21]])

### seperationg into two part X and y

In [28]:
X = padded_training_sequence[:,:-1]

In [29]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        ...,
        [  0,   0, 158,  ...,   2,   3,  40],
        [  0, 158, 223,  ...,   3,  40,   1],
        [158, 223,  10,  ...,  40,   1,  41]])

In [30]:
y = padded_training_sequence[:,-1]

In [31]:
y

tensor([  2,   3,   4,   6,   7,   8,   9,  10,  11,  12,  13,   1,  14,  15,
         16,  17,   6,  18,  19,  20,  21,  16,  22,  23,  24,  25,  26,   6,
         27,  28,  29,  30,   5,  31,  32,  21,  33,  34,  35,  36,   1,  37,
         38,   1,  39,   3,  40,   1,  41,  42,  43,   1,  44,  21,  45,   1,
         46,  47,  48,  49,  50,  51,  52,   1,   3,  21,  53,  54,  55,  56,
          6,  57,  58,  50,  59,  37,  60,  61,  21,   1,   3,  10,  63,  64,
         65,  66,  67,  68,  40,  24,  69,  21,  71,   6,  72,  73,   1,  74,
         50,  75,  48,  20,  76,  77,  48,  78,  21,   1,   3,  79,  80,  81,
         10,   1,  82,  64,  42,  83,  84,  85,  86,  40,  87,  21,  89,  90,
         91,  61,  92,  93,  94,  95,  96,   1,  97,  21,   1,  99, 100, 101,
        102, 103, 104, 101,  14, 105,  56,   6, 106, 107,  21,  27, 109, 110,
        111,  61,   1,  74,  38, 112, 113,  26, 114, 115,  21, 116,   6, 117,
        118, 119, 120, 121, 122, 123,   6,  18, 124,  21, 126, 1

In [32]:
len(X)

555

In [33]:
len(y)

555

# Custom Dataset and DataLoader

In [34]:
class CustomDataset(Dataset):
  def __init__(self, X, y):
    self.X = X
    self.y = y

  def __len__(self):
    return self.X.shape[0]

  def __getitem__(self, indx):
    return self.X[indx], self.y[indx]

In [35]:
dataset = CustomDataset(X, y)

In [36]:
len(dataset)

555

In [37]:
dataloader = DataLoader(dataset, batch_size = 32, shuffle=True)

In [38]:
# verifyinf dataloader
for input, output in dataloader:
  print(input, output)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   5,   6,   7,   8,   9,  10,
          11,  12,  13,   1,  14,  15,  16,  17,   6,  18],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   1, 214],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 110,
         175, 176, 177,  10, 178, 179,  10,  50, 180, 181],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,  11],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  11,
         184,  76,  92,   1,   3, 185,  36, 186, 187,  50],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,  62, 259,  22,   6, 260,  40,   1, 168, 169],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           1,   7,  37,  10, 272, 253,  10,  50,  93, 273],
        [  0,   0,   0,   0

In [39]:
X.shape

torch.Size([555, 24])

In [40]:
y.shape

torch.Size([555])

In [41]:
len(vocab)

284

# LSTM Cell

In [42]:
class LSTMModel(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, 100)
    self.lstm = nn.LSTM(100, 150, batch_first= True)
    self.fc = nn.Linear(150, vocab_size)

  def forward(self, x):
    embedded = self.embedding(x)
    intermediate_hidden_states,(final_hidden_state,final_cell_state) = self.lstm(embedded)
    output = self.fc(final_hidden_state.squeeze(0))
    return output

In [43]:
model = LSTMModel(len(vocab))

In [44]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [45]:
model.to(device)

LSTMModel(
  (embedding): Embedding(284, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=284, bias=True)
)

In [46]:
len(vocab)

284

In [47]:
len(dataset)

555

In [48]:
x = nn.Embedding(284,100)
y = nn.LSTM(100,150,batch_first=True)
z = nn.Linear(150, 284)

In [49]:
dataset[0][0]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [50]:
dataset[0][0].shape

torch.Size([24])

In [51]:
dataset[0][0].unsqueeze(0).shape

torch.Size([1, 24])

In [52]:
a = dataset[0][0].unsqueeze(0)
a

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [53]:
x(a) ## embedding result

tensor([[[-0.0407,  1.1051,  1.0537,  ...,  2.0384,  0.5428,  0.9187],
         [-0.0407,  1.1051,  1.0537,  ...,  2.0384,  0.5428,  0.9187],
         [-0.0407,  1.1051,  1.0537,  ...,  2.0384,  0.5428,  0.9187],
         ...,
         [-0.0407,  1.1051,  1.0537,  ...,  2.0384,  0.5428,  0.9187],
         [-0.0407,  1.1051,  1.0537,  ...,  2.0384,  0.5428,  0.9187],
         [ 1.7843,  0.9535,  0.1136,  ...,  0.6912, -2.7425, -1.6825]]],
       grad_fn=<EmbeddingBackward0>)

In [54]:
x(a).shape

torch.Size([1, 24, 100])

In [55]:
b = x(a)

In [56]:
y(b) ## Giving to LSTM

(tensor([[[ 0.1044,  0.1133,  0.0035,  ..., -0.0553,  0.2560, -0.0795],
          [ 0.1689,  0.1749,  0.0267,  ..., -0.1003,  0.4109, -0.1123],
          [ 0.2051,  0.2056,  0.0469,  ..., -0.1321,  0.4945, -0.1240],
          ...,
          [ 0.2640,  0.2318,  0.0838,  ..., -0.1933,  0.6073, -0.1134],
          [ 0.2640,  0.2318,  0.0837,  ..., -0.1933,  0.6074, -0.1133],
          [ 0.1332,  0.1138,  0.0725,  ..., -0.1505,  0.5452, -0.0820]]],
        grad_fn=<TransposeBackward0>),
 (tensor([[[ 0.1332,  0.1138,  0.0725,  0.1678, -0.0435, -0.0296, -0.1327,
            -0.0286, -0.1079, -0.2556, -0.1981, -0.0878,  0.0288, -0.0497,
             0.0869,  0.0994, -0.2120, -0.1838, -0.0221,  0.0730, -0.1395,
            -0.1325,  0.0350, -0.0895, -0.1817, -0.0007, -0.0034, -0.1015,
             0.0313,  0.0287, -0.1516, -0.3326,  0.0685,  0.0659,  0.4237,
             0.2063, -0.1203, -0.1999,  0.0131, -0.1633,  0.0778,  0.0125,
            -0.2662, -0.1735, -0.0183,  0.1772, -0.0504,  0.01

In [57]:
len(y(b))

2

In [58]:
c, d = y(b)

In [59]:
c.shape  #Set of all intermediate hidden state

torch.Size([1, 24, 150])

In [60]:
len(d)

2

In [61]:
e, f = d

In [62]:
e.shape #Cell state

torch.Size([1, 1, 150])

In [63]:
f.shape

torch.Size([1, 1, 150])

In [64]:
f_temp = f.squeeze(0).shape
f_temp

torch.Size([1, 150])

In [65]:
f_temp = f.squeeze(0)

In [66]:
z(f_temp)

tensor([[-0.2439, -0.1385,  0.1630,  0.3906,  0.1766,  0.0070, -0.1256,  0.0713,
         -0.0910,  0.0043, -0.0601, -0.1076,  0.0626, -0.0268, -0.1509,  0.3929,
         -0.5075,  0.0578, -0.3217, -0.1353, -0.1022, -0.2019,  0.0397,  0.2614,
         -0.1406, -0.0522, -0.0794,  0.2533, -0.2726,  0.0089,  0.0063,  0.0115,
          0.2276,  0.1262,  0.0997,  0.1443,  0.1101,  0.1011, -0.2679, -0.2983,
         -0.0041,  0.0326, -0.1859,  0.1991,  0.0199,  0.1768, -0.0393, -0.1736,
          0.1490,  0.1665, -0.1360,  0.3967,  0.0273,  0.0228, -0.2938,  0.2429,
         -0.3246,  0.0473, -0.3545, -0.1707,  0.2057, -0.1018,  0.1819,  0.0090,
         -0.0031,  0.0466,  0.0885,  0.0354,  0.3165, -0.1748, -0.3579,  0.1775,
          0.1161, -0.1267,  0.1312,  0.0784,  0.3390, -0.0595,  0.2393, -0.1818,
          0.2067, -0.3196,  0.1463,  0.3395,  0.3003,  0.0411, -0.1354,  0.2946,
          0.0299, -0.2589,  0.0531,  0.1165,  0.0172,  0.2038,  0.1118, -0.0848,
          0.0508,  0.4104,  

In [67]:
len(f_temp[0])

150

In [68]:
len(z(f_temp)[0])

284

In [69]:
len(vocab)

284

In [70]:
for batch_x, batch_y in dataloader:
  print(batch_x, batch_y)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   1,  28, 227,  56, 228,  38],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,  98,   1],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,  11,  50, 153, 170, 232],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,  38,   1,   4, 170,  10, 153, 171, 172],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,  11],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 126, 127,
         223,  10,   1, 197, 224, 149, 225,  50,   1,   3],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0, 158, 223],
        [  0,   0,   0,   0

# Training Loop

In [71]:
epochs = 50
learning_rate = 0.001

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)


# training loop

for epoch in range(epochs):
  total_loss = 0

  for batch_x, batch_y in dataloader:

    batch_x, batch_y = batch_x.to(device), batch_y.to(device)

    optimizer.zero_grad()

    output = model(batch_x)

    loss = criterion(output, batch_y)

    loss.backward()

    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch + 1}, Loss: {total_loss:.4f}")

Epoch: 1, Loss: 101.1358
Epoch: 2, Loss: 95.2949
Epoch: 3, Loss: 87.1700
Epoch: 4, Loss: 81.2787
Epoch: 5, Loss: 75.9856
Epoch: 6, Loss: 70.5924
Epoch: 7, Loss: 65.3905
Epoch: 8, Loss: 58.8916
Epoch: 9, Loss: 54.3063
Epoch: 10, Loss: 49.3259
Epoch: 11, Loss: 44.5726
Epoch: 12, Loss: 39.6905
Epoch: 13, Loss: 35.0825
Epoch: 14, Loss: 31.3209
Epoch: 15, Loss: 27.6277
Epoch: 16, Loss: 24.7449
Epoch: 17, Loss: 22.0150
Epoch: 18, Loss: 19.1778
Epoch: 19, Loss: 17.5642
Epoch: 20, Loss: 15.4349
Epoch: 21, Loss: 13.8097
Epoch: 22, Loss: 12.2530
Epoch: 23, Loss: 11.3261
Epoch: 24, Loss: 10.0105
Epoch: 25, Loss: 9.3342
Epoch: 26, Loss: 8.4688
Epoch: 27, Loss: 7.7810
Epoch: 28, Loss: 7.0261
Epoch: 29, Loss: 6.5795
Epoch: 30, Loss: 6.0639
Epoch: 31, Loss: 5.6713
Epoch: 32, Loss: 5.3129
Epoch: 33, Loss: 5.1113
Epoch: 34, Loss: 4.7889
Epoch: 35, Loss: 4.6614
Epoch: 36, Loss: 4.2891
Epoch: 37, Loss: 4.1946
Epoch: 38, Loss: 3.8612
Epoch: 39, Loss: 3.6936
Epoch: 40, Loss: 3.5758
Epoch: 41, Loss: 3.4110


# Prediction

In [72]:
max(len_list)

25

In [73]:
def prediction(model,vocab,text):

  #tokenize
  tokenized_text = word_tokenize(text.lower())

  # print(tokenized_text)

  #numerical indices
  numerical_text = text_to_indices(tokenized_text,vocab)

  # print(numerical_text)

  #padding
  padded_text = torch.tensor([0]* (25-len(numerical_text)) + numerical_text , dtype=torch.long).unsqueeze(0)

  # print(padded_text)

  # print(len(padded_text))

  # print(padded_text.shape)

  #send to model
  output = model(padded_text)

  # print("model's output",output)

  # print("printing total_elements",len(output[0]))

  #predicted index

  value, index = torch.max(output,dim=1)

  # print(f"printing value and index {value}, {index}")

  # print(f"printing  index  {index}")

  # print("printing the word ")

  # print(list(vocab.keys())[index])

  #merge with text

  return text + " " + list(vocab.keys())[index]


In [74]:
prediction(model, vocab, "He chose a seat beside the")

'He chose a seat beside the window'

In [75]:
document.split('\n')

['The Last Train Journey',
 '',
 'On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.',
 'The station was nearly empty except for a few passengers waiting quietly on wooden benches.',
 'A loud whistle echoed through the air as the final train of the night slowly entered the platform.',
 '',
 'Daniel checked the ticket in his pocket and walked toward the train.',
 'The metal doors opened with a creaking sound and warm air rushed outside.',
 'Inside the train, yellow lights flickered softly above rows of empty seats.',
 '',
 'He chose a seat beside the window and placed his bag carefully near his feet.',
 'As the train began to move, the city lights slowly disappeared behind thick clouds of fog.',
 'Snow started falling gently outside while distant mountains appeared under the moonlight.',
 '',
 'Across the aisle sat an elderly woman reading an old book with a blue cover.',
 'Every few minutes she looked outside the window as if searching for

# Generate Automatically

In [76]:
import time
num_tokens = 14
input_text= 'Daniel checked the ticket'

for i in range(num_tokens):
  output_text = prediction(model,vocab,input_text)
  print(output_text)
  input_text = output_text
  time.sleep(0.5)

Daniel checked the ticket in
Daniel checked the ticket in his
Daniel checked the ticket in his pocket
Daniel checked the ticket in his pocket and
Daniel checked the ticket in his pocket and walked
Daniel checked the ticket in his pocket and walked toward
Daniel checked the ticket in his pocket and walked toward the
Daniel checked the ticket in his pocket and walked toward the train
Daniel checked the ticket in his pocket and walked toward the train .
Daniel checked the ticket in his pocket and walked toward the train . .
Daniel checked the ticket in his pocket and walked toward the train . . .
Daniel checked the ticket in his pocket and walked toward the train . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . .


# Accuracy Calculation

In [92]:
def calculate_accuracy(model, dataloader, device):
  model.eval() #set the model to evaluation mode

  correct = 0
  total = 0

  with torch.no_grad():
    for batch_x, batch_y in dataloader:
      batch_x, batch_y = batch_x.to(device), batch_y.to(device)

      # get model prediction
      output = model(batch_x)

      # get the predicted word indices
      _, predicted = torch.max(output, dim=1)

        #print("print predicted word indices",predicted)

      # Compare with actual label

        #print("print y label indices", batch_y)
        #print(predicted == batch_y)
      correct += (predicted == batch_y).sum().item()

        #print(correct)
      total += batch_y.size(0)

    accuracy = correct / total * 100
    return accuracy


In [94]:
accuracy = calculate_accuracy(model,dataloader,device)

print(f" Model accuracy {accuracy :.2f}%")

 Model accuracy 96.94%
